package com.bryan.finance.enums;

public enum Tables {
	ADDRESSES, BANNED_USERS, EXPENSES, INCOME, INVESTMENTS, MONTHLY_TOTALS,
	MONTHLY_EXP_CATGR, MONTHLY_TRANSACTIONS, PAY_GRADES, SAVINGS, SITES, USERS
}
