package com.bryan.finance.enums;

public enum Views {
    CURRENT_BALANCE_TODAY, FUTURE_BALANCE_SUM, FUTURE_TRANSACTIONS_SUM, SAVINGS_BALANCE,
    TOTAL_HOUSE_SAVINGS, TRUE_BALANCE, UNPAID_CREDITS_SUM
}
